### ISSUE TITLE
Составить список требуемых технологий для нового проекта 

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [AnatoliiStepaniuk/FlowerExpert#1]

**Comment by romach** [comment]
* Spring;
* Логирование - выбрать одну из библиотек: SLF4J, Log4j, ...
* Тестирование - JUnit, Mockito;

**Фронтенд** - с этим сложно, мне приходит в голову только AngularJS - нужно знать JS, есть еще такая штука Java Server Faces (я о ней только слышал) - автоматически генерирует JavaScript.

**БД** - Hibernate, Liquibase (для миграций БД);

**Comment by AnatoliiStepaniuk** [comment]
Сейчас добавлю это в список на вики.
